Handle IP address changes of units
canonical/mysql-operator pull request #232
Opened 2023-06-21 15:19 UTC by shayancanonical

## Issue
We are currently not handling the IP address change of a unit in the cluster.

## Solution
Handle the IP address change of a unit (whether in a cluster or a single node).

Steps to recover involve:
1. Remove plugin `group_replication`
2. Update `report_host` in the custom mysqld config file and restart mysqld
3. Add node back to cluster (or recreate cluster if there is only 1 unit in the cluster)

If the transaction set in the unit is a subset of the transaction set in the cluster, then upon addition into the cluster, distributed recovery will be in effect. Else, the data will be cloned from one of the units in the cluster.

## Considerations
- How will scaling down to 1 unit (preserving the data volume), recovering from IP address change, and then scaling up effect SST (because the GTID may be different after re-creating a cluster in the recovery process)?

2023-06-21 15:24 UTC, shayancanonical commented on lib/charms/mysql/v0/mysql.py
>  )
TODO: update the lib patch version

2023-06-22 05:37 UTC, delgod requested changes

2023-06-22 05:37 UTC, delgod commented on lib/charms/mysql/v0/mysql.py
> +        disable_super_read_only_command = "SET GLOBAL super_read_only = 0"
Just Q: why do we need to reset super_read_only before disabling GR?

2023-06-22 05:37 UTC, delgod commented on src/charm.py
> +            unit_ip = socket.gethostbyname(hostname)
I think it is possible to get `127.0.0.1` here under some `/etc/hosts` configuration.
maybe https://stackoverflow.com/a/28950776

2023-06-22 05:37 UTC, delgod commented on src/charm.py
> +                    "Restarting mysqld, since it was started with --super-read-only option"
But why do we need to restart? the read-only mode can be removed without restart

2023-06-22 20:50 UTC, paulomach commented on lib/charms/mysql/v0/mysql.py
> +        retrieve_variable_command = f"SHOW VARIABLES LIKE '{variable_name}'"
```suggestion
        retrieve_variable_command = f"SHOW VARIABLES WHERE VARIABLE_NAME '{variable_name}'"
```
or
```suggestion
        retrieve_variable_command = f"SELECT @@`{variable_name}`"
```

2023-06-26 09:13 UTC, taurus-forever commented
@shayancanonical as discussed, it smells a bit. After discussion with @delgod , let's try the second approach (keep cluster configured on DNS names, but add manual /etc/hosts handling (like legacy charm did).
Let's compare the pros/cons for both cases before merging this approach. Thank you!

2023-06-29 14:22 UTC, shayancanonical commented
Closing in lieu of the implementation in https://github.com/canonical/mysql-operator/pull/237 (which is far cleaner and modular)

2023-06-29 14:22 UTC, closed without merging